insert into procedures (id, name, billing_number) values (1, 'Revision of Nonaut Sub in L Thumb Phalanx, Open Approach', '9439');
insert into procedures (id, name, billing_number) values (2, 'Extirpation of Matter from R Thyroid Lobe, Open Approach', '4259');
insert into procedures (id, name, billing_number) values (3, 'Traction of Right Inguinal Region', '9516');
insert into procedures (id, name, billing_number) values (4, 'Bypass Innom Art to Bi Low Leg Art w Autol Art, Open', '1431');
insert into procedures (id, name, billing_number) values (5, 'Removal of Spacer from Left Sacroiliac Joint, Open Approach', '8007');
insert into procedures (id, name, billing_number) values (6, 'Excision of Right Mastoid Sinus, Percutaneous Approach', '8461');
insert into procedures (id, name, billing_number) values (7, 'Excision of Upper Vein, Open Approach', '9307');
insert into procedures (id, name, billing_number) values (8, 'Insert of Radioact Elem into Periton Cav, Perc Endo Approach', '0820');
insert into procedures (id, name, billing_number) values (9, 'Repair Left External Auditory Canal, Open Approach', '9502');
insert into procedures (id, name, billing_number) values (10, 'Repair GI Sys in POC with Oth Dev, Via Opening', '4574');
insert into procedures (id, name, billing_number) values (11, 'Occlusion of Right Parotid Duct, Open Approach', '3845');
insert into procedures (id, name, billing_number) values (12, 'Destruction of Inferior Vena Cava, Open Approach', '4133');
insert into procedures (id, name, billing_number) values (13, 'Destruction of Left Pulmonary Artery, Perc Endo Approach', '9801');
insert into procedures (id, name, billing_number) values (14, 'Revision of Radioactive Element in Neck, External Approach', '5595');
insert into procedures (id, name, billing_number) values (15, 'Extirpation of Matter from Urethra, Open Approach', '9607');
insert into procedures (id, name, billing_number) values (16, 'Division of Left Temporal Bone, Percutaneous Approach', '864');
insert into procedures (id, name, billing_number) values (17, 'Replace L Humeral Shaft w Autol Sub, Perc Endo', '5792');
insert into procedures (id, name, billing_number) values (18, 'Introduce Oth Antineoplastic in Central Art, Open', '8832');
insert into procedures (id, name, billing_number) values (19, 'Fusion L Metatarsotars Jt w Nonaut Sub, Perc Endo', '7811');
insert into procedures (id, name, billing_number) values (20, 'Excision of Left Breast, External Approach, Diagnostic', '2721');
insert into procedures (id, name, billing_number) values (21, 'Drainage of Sacral Plexus, Open Approach', '0043');
insert into procedures (id, name, billing_number) values (22, 'Division of Facial Muscle, Open Approach', '5381');
insert into procedures (id, name, billing_number) values (23, 'Excision of Left Foot Tendon, Percutaneous Approach', '7694');
insert into procedures (id, name, billing_number) values (24, 'Extirpation of Matter from R Finger Phalanx, Perc Approach', '0886');
insert into procedures (id, name, billing_number) values (25, 'Excision of Left Nipple, External Approach', '3818');
insert into procedures (id, name, billing_number) values (26, 'Insertion of Intraluminal Device into Duodenum, Endo', '7759');
insert into procedures (id, name, billing_number) values (27, 'Remove Nonaut Sub from R Metatarsotars Jt, Perc Endo', '5472');
insert into procedures (id, name, billing_number) values (28, 'Release Left Large Intestine, Endo', '9651');
insert into procedures (id, name, billing_number) values (29, 'Excision of Left Atrium, Percutaneous Approach', '5362');
insert into procedures (id, name, billing_number) values (30, 'Removal of Autologous Tissue Substitute from Left Eye, Endo', '8863');
insert into procedures (id, name, billing_number) values (31, 'Plain Radiography of Bi Pulm Vein using L Osm Contrast', '1239');
insert into procedures (id, name, billing_number) values (32, 'Insertion of Int Fix into L Glenoid Cav, Perc Approach', '4529');
insert into procedures (id, name, billing_number) values (33, 'Repair Left Toe Phalangeal Joint, Perc Endo Approach', '8095');
insert into procedures (id, name, billing_number) values (34, 'Revision of Drainage Device in Upper Jaw, Perc Endo Approach', '8889');
insert into procedures (id, name, billing_number) values (35, 'Drainage of Right External Jugular Vein, Open Approach', '9374');
insert into procedures (id, name, billing_number) values (36, 'Insert of Intralum Dev into L Less Saphenous, Perc Approach', '8742');
insert into procedures (id, name, billing_number) values (37, 'Bypass Cystic Duct to Caud Duct w Intralum Dev, Open', '1122');
insert into procedures (id, name, billing_number) values (38, 'Destruction of Right Abdomen Tendon, Perc Endo Approach', '8548');
insert into procedures (id, name, billing_number) values (39, 'Destruction of Lumbar Vertebral Joint, Open Approach', '8715');
insert into procedures (id, name, billing_number) values (40, 'Replace L Ext Iliac Art w Synth Sub, Perc Endo', '3929');
insert into procedures (id, name, billing_number) values (41, 'Transfuse Nonaut Frozen Red Cells in Periph Vein, Perc', '8428');
insert into procedures (id, name, billing_number) values (42, 'Drainage of Thoracic Sympathetic Nerve, Perc Endo Approach', '8473');
insert into procedures (id, name, billing_number) values (43, 'Excision of Left Upper Leg, Percutaneous Approach', '2094');
insert into procedures (id, name, billing_number) values (44, 'Extraction of Right Vocal Cord, Via Opening', '8009');
insert into procedures (id, name, billing_number) values (45, 'Revision of Synthetic Substitute in Sacrum, Perc Approach', '835');
insert into procedures (id, name, billing_number) values (46, 'Dilation of L Fem Art using Drug Blln, Perc Endo Approach', '9749');
insert into procedures (id, name, billing_number) values (47, 'Drainage of Lower Lip, Percutaneous Approach', '0716');
insert into procedures (id, name, billing_number) values (48, 'Removal of Nonaut Sub from R Femur Shaft, Open Approach', '8382');
insert into procedures (id, name, billing_number) values (49, 'Revision of Synth Sub in L Acetabulum, Extern Approach', '7867');
insert into procedures (id, name, billing_number) values (50, 'Release Left Rib, Percutaneous Endoscopic Approach', '3195');
insert into procedures (id, name, billing_number) values (51, 'Drainage of Left Upper Leg Tendon, Open Approach, Diagnostic', '3607');
insert into procedures (id, name, billing_number) values (52, 'Excision of Right Temporomandibular Joint, Open Approach', '3727');
insert into procedures (id, name, billing_number) values (53, 'Bypass R Com Iliac Art to R Renal A w Nonaut Sub, Open', '0863');
insert into procedures (id, name, billing_number) values (54, 'Fusion Lumsac Jt w Nonaut Sub, Ant Appr A Col, Perc Endo', '3961');
insert into procedures (id, name, billing_number) values (55, 'Insertion of Ext Fix into L Tarsal, Perc Approach', '0983');
insert into procedures (id, name, billing_number) values (56, 'Dilate L Fem Art, Bifurc, w 2 Intralum Dev, Open', '2932');
insert into procedures (id, name, billing_number) values (57, 'Occlusion of Hepatic Artery, Open Approach', '2182');
insert into procedures (id, name, billing_number) values (58, 'Bypass L Ureter to Colocutan with Autol Sub, Open Approach', '0795');
insert into procedures (id, name, billing_number) values (59, 'Revision of Autol Sub in L Up Extrem, Perc Endo Approach', '6652');
insert into procedures (id, name, billing_number) values (60, 'Inspection of Left Tarsal Joint, Perc Endo Approach', '8252');
insert into procedures (id, name, billing_number) values (61, 'Compression of Left Toe using Intermittent Pressure Device', '9739');
insert into procedures (id, name, billing_number) values (62, 'Replace R Hip Jt w Metal on Poly, Uncement, Open', '9996');
insert into procedures (id, name, billing_number) values (63, 'Revision of Int Fix in R Toe Phalanx Jt, Perc Approach', '7664');
insert into procedures (id, name, billing_number) values (64, 'Drainage of Right Patella, Perc Endo Approach, Diagn', '185');
insert into procedures (id, name, billing_number) values (65, 'Alteration of R Ankle with Synth Sub, Perc Endo Approach', '8422');
insert into procedures (id, name, billing_number) values (66, 'Dilate L Com Iliac Art, Bifurc, w 4 Drug-elut, Perc Endo', '9411');
insert into procedures (id, name, billing_number) values (67, 'Removal of Int Fix from R Low Femur, Perc Approach', '5594');
insert into procedures (id, name, billing_number) values (68, 'Revision of Synth Sub in R Femur Shaft, Extern Approach', '1164');
insert into procedures (id, name, billing_number) values (69, 'Insertion of Tissue Expander into Left Nipple, Open Approach', '5694');
insert into procedures (id, name, billing_number) values (70, 'Insert of Infusion Dev into R Brach Art, Perc Endo Approach', '3561');
insert into procedures (id, name, billing_number) values (71, 'Fragmentation in Right Hepatic Duct, Percutaneous Approach', '8712');
insert into procedures (id, name, billing_number) values (72, 'Replacement of Intracran Vein with Synth Sub, Open Approach', '5994');
insert into procedures (id, name, billing_number) values (73, 'Excision of R Ext Auditory Canal, Perc Endo Approach', '4421');
insert into procedures (id, name, billing_number) values (74, 'Fusion of Right Ankle Joint with Autol Sub, Open Approach', '9602');
insert into procedures (id, name, billing_number) values (75, 'Reposition Right Clavicle with Int Fix, Open Approach', '9753');
insert into procedures (id, name, billing_number) values (76, 'Revision of Drain Dev in R Toe Phalanx Jt, Open Approach', '5164');
insert into procedures (id, name, billing_number) values (77, 'Repair Sacral Plexus, Open Approach', '2009');
insert into procedures (id, name, billing_number) values (78, 'Fusion of Left Shoulder Joint with Int Fix, Perc Approach', '1472');
insert into procedures (id, name, billing_number) values (79, 'Restrict Sigmoid Colon w Extralum Dev, Perc Endo', '7678');
insert into procedures (id, name, billing_number) values (80, 'Reposition Occipital-cervical Joint, Open Approach', '1723');
insert into procedures (id, name, billing_number) values (81, 'Non-inv Instrument Status Assess w Aerodynam Funct Equip', '8382');
insert into procedures (id, name, billing_number) values (82, 'Removal of Synth Sub from R Finger Phalanx Jt, Open Approach', '5493');
insert into procedures (id, name, billing_number) values (83, 'Revision of Infusion Device in L Knee Jt, Perc Endo Approach', '5141');
insert into procedures (id, name, billing_number) values (84, 'Destruction of L Hand Subcu/Fascia, Perc Approach', '8593');
insert into procedures (id, name, billing_number) values (85, 'Bypass R Subclav Art to L Up Arm Art, Open Approach', '5591');
insert into procedures (id, name, billing_number) values (86, 'Extirpation of Matter from Left Maxilla, Perc Endo Approach', '4881');
insert into procedures (id, name, billing_number) values (87, 'Extirpate of Matter from Spinal Meninges, Perc Endo Approach', '8162');
insert into procedures (id, name, billing_number) values (88, 'Release Left Upper Extremity Lymphatic, Perc Endo Approach', '8814');
insert into procedures (id, name, billing_number) values (89, 'Bypass Pulm Trunk from Innom Art w No Dev, Perc Endo', '0473');
insert into procedures (id, name, billing_number) values (90, 'Fluoroscopy of R Renal Art using Oth Contrast, Laser Intraop', '5282');
insert into procedures (id, name, billing_number) values (91, 'Excision of Female Perineum, Perc Endo Approach, Diagn', '8852');
insert into procedures (id, name, billing_number) values (92, 'Transplant of Hepatobil & Pancr into POC, Perc Endo Approach', '7962');
insert into procedures (id, name, billing_number) values (93, 'Extirpation of Matter from Left Thorax Muscle, Open Approach', '1509');
insert into procedures (id, name, billing_number) values (94, 'Fusion R Metacarpophal Jt w Synth Sub, Perc Endo', '8441');
insert into procedures (id, name, billing_number) values (95, 'Dilation of Descending Colon, Via Opening', '9655');
insert into procedures (id, name, billing_number) values (96, 'Drainage of Right Neck Lymphatic, Perc Approach, Diagn', '864');
insert into procedures (id, name, billing_number) values (97, 'Reposition Ascending Colon, External Approach', '8098');
insert into procedures (id, name, billing_number) values (98, 'Removal of Nonaut Sub from Fem Perineum, Perc Endo Approach', '2049');
insert into procedures (id, name, billing_number) values (99, 'Supplement R Tunica Vaginalis with Nonaut Sub, Open Approach', '8571');
insert into procedures (id, name, billing_number) values (100, 'Bypass Pulm Trunk from Subclav w Autol Vn, Perc Endo', '5300');
insert into procedures (id, name, billing_number) values (101, 'Removal of Drainage Device from Upper Muscle, Perc Approach', '9964');
insert into procedures (id, name, billing_number) values (102, 'Supplement R Hand Vein with Nonaut Sub, Perc Endo Approach', '3491');
insert into procedures (id, name, billing_number) values (103, 'HDR Brachytherapy of Soft Palate using Iodine 125', '7592');
insert into procedures (id, name, billing_number) values (104, 'Chiropractic Manipulation Thoracic Region, Long, Short Lever', '5182');
insert into procedures (id, name, billing_number) values (105, 'Transfer Left Trunk Bursa and Ligament, Perc Endo Approach', '8889');
insert into procedures (id, name, billing_number) values (106, 'Excision of Left External Iliac Artery, Perc Approach', '8154');
insert into procedures (id, name, billing_number) values (107, 'CT Scan Inf Vena Cava w L Osm Contrast, Unenh, Enhance', '2641');
insert into procedures (id, name, billing_number) values (108, 'Group Counsel for Substance Abuse, Motivational Enhance', '9751');
insert into procedures (id, name, billing_number) values (109, 'Supplement Vagus Nerve with Autol Sub, Perc Endo Approach', '7693');
insert into procedures (id, name, billing_number) values (110, 'Drainage of Bilateral Epididymis, Open Approach, Diagnostic', '9541');
insert into procedures (id, name, billing_number) values (111, 'Reposition Left Hip Joint with Ext Fix, Perc Endo Approach', '2642');
insert into procedures (id, name, billing_number) values (112, 'Extirpation of Matter from Intracranial Vein, Perc Approach', '0125');
insert into procedures (id, name, billing_number) values (113, 'Inspection of Right Sternoclavicular Joint, Open Approach', '9337');
insert into procedures (id, name, billing_number) values (114, 'Drainage of Right Upper Lung Lobe, Perc Endo Approach', '664');
insert into procedures (id, name, billing_number) values (115, 'Bypass R Fallopian Tube to R Fallop w Synth Sub, Perc Endo', '2059');
insert into procedures (id, name, billing_number) values (116, 'Release Right Middle Lung Lobe, Endo', '5719');
insert into procedures (id, name, billing_number) values (117, 'Drainage of Right Humeral Head with Drain Dev, Open Approach', '5522');
insert into procedures (id, name, billing_number) values (118, 'Excision of Right Internal Iliac Artery, Open Approach', '4531');
insert into procedures (id, name, billing_number) values (119, 'Drainage of Urethra, Open Approach, Diagnostic', '5195');
insert into procedures (id, name, billing_number) values (120, 'Replace R Hand Skin w Nonaut Sub, Full Thick, Extern', '6829');
insert into procedures (id, name, billing_number) values (121, 'Inspection of Left Metacarpocarpal Joint, Open Approach', '8182');
insert into procedures (id, name, billing_number) values (122, 'Remove Infusion Dev from R Finger Phalanx Jt, Open', '3796');
insert into procedures (id, name, billing_number) values (123, 'Transfer Glossophar Nrv to Oculomotor N, Open Approach', '9213');
insert into procedures (id, name, billing_number) values (124, 'Dilation of Duodenum with Intraluminal Device, Via Opening', '6879');
insert into procedures (id, name, billing_number) values (125, 'Excision of Transverse Colon, Perc Endo Approach, Diagn', '3606');
insert into procedures (id, name, billing_number) values (126, 'Plain Radiography of Right Knee using Other Contrast', '3984');
insert into procedures (id, name, billing_number) values (127, 'Drainage of Anus, External Approach', '3250');
insert into procedures (id, name, billing_number) values (128, 'Repair Right Ureter, Via Natural or Artificial Opening', '4949');
insert into procedures (id, name, billing_number) values (129, 'Alteration of Right Upper Eyelid, Open Approach', '4439');
insert into procedures (id, name, billing_number) values (130, 'Bypass R Ureter to L Ureter w Synth Sub, Perc Endo', '585');
insert into procedures (id, name, billing_number) values (131, 'Release Left Main Bronchus, Endo', '0881');
insert into procedures (id, name, billing_number) values (132, 'Drainage of R Glenoid Cav with Drain Dev, Open Approach', '1761');
insert into procedures (id, name, billing_number) values (133, 'Drainage of R Up Extrem Bursa/Lig, Open Approach, Diagn', '5164');
insert into procedures (id, name, billing_number) values (134, 'Insertion of Bone Stim into Facial Bone, Perc Approach', '3179');
insert into procedures (id, name, billing_number) values (135, 'Fusion Lum Jt w Autol Sub, Post Appr P Col, Open', '0115');
insert into procedures (id, name, billing_number) values (136, 'Reposition Left Palatine Bone, External Approach', '4514');
insert into procedures (id, name, billing_number) values (137, 'Resection of Right Knee Bursa and Ligament, Open Approach', '5375');
insert into procedures (id, name, billing_number) values (138, 'ROM & Jt Mobility Treatment of Integu Body using Prosthesis', '9957');
insert into procedures (id, name, billing_number) values (139, 'LDR Brachytherapy of Nasopharynx using Iodine 125', '9183');
insert into procedures (id, name, billing_number) values (140, 'Excision of Esophagus, Perc Endo Approach, Diagn', '7766');
insert into procedures (id, name, billing_number) values (141, 'Bypass R Ureter to Colocutan with Autol Sub, Open Approach', '8145');
insert into procedures (id, name, billing_number) values (142, 'Extirpation of Matter from Esophagus, Percutaneous Approach', '1722');
insert into procedures (id, name, billing_number) values (143, 'Ultrasonography of Right Ovary using Other Contrast', '1911');
insert into procedures (id, name, billing_number) values (144, 'Extirpation of Matter from Coccygeal Glomus, Open Approach', '0479');
insert into procedures (id, name, billing_number) values (145, 'Fluoroscopy of Left Jugular Veins', '8918');
insert into procedures (id, name, billing_number) values (146, 'Drainage of Right Mastoid Sinus, Perc Approach, Diagn', '1029');
insert into procedures (id, name, billing_number) values (147, 'Bypass 1 Cor Art from R Int Mammary w Autol Vn, Perc Endo', '0159');
insert into procedures (id, name, billing_number) values (148, 'Bypass Stomach to Duodenum, Open Approach', '7749');
insert into procedures (id, name, billing_number) values (149, 'Inspection of Right Ankle Joint, Open Approach', '3930');
insert into procedures (id, name, billing_number) values (150, 'Division of R Low Extrem Bursa/Lig, Open Approach', '9093');
insert into procedures (id, name, billing_number) values (151, 'Repair Left Occipital Bone, Percutaneous Approach', '3975');
insert into procedures (id, name, billing_number) values (152, 'Supplement Right Hand with Autol Sub, Open Approach', '636');
insert into procedures (id, name, billing_number) values (153, 'Drainage of Right Ethmoid Sinus, Perc Approach, Diagn', '8835');
insert into procedures (id, name, billing_number) values (154, 'Extirpation of Matter from Appendix, Open Approach', '8095');
insert into procedures (id, name, billing_number) values (155, 'Removal of Autol Sub from Larynx, Open Approach', '8155');
insert into procedures (id, name, billing_number) values (156, 'Removal of Nonaut Sub from L Clavicle, Perc Endo Approach', '9749');
insert into procedures (id, name, billing_number) values (157, 'Excision of Left Tunica Vaginalis, Perc Endo Approach', '2264');
insert into procedures (id, name, billing_number) values (158, 'Drainage of Right Upper Arm Skin, External Approach', '5297');
insert into procedures (id, name, billing_number) values (159, 'Supplement Right Lower Femur with Autol Sub, Open Approach', '303');
insert into procedures (id, name, billing_number) values (160, 'Supplement Innominate Artery with Autol Sub, Perc Approach', '1609');
insert into procedures (id, name, billing_number) values (161, 'Occlusion L Axilla Art w Intralum Dev, Perc Endo', '7992');
insert into procedures (id, name, billing_number) values (162, 'Drainage of R Ext Jugular Vein with Drain Dev, Perc Approach', '4594');
insert into procedures (id, name, billing_number) values (163, 'Exercise Treatment of Circ Body using Mech Equipment', '9329');
insert into procedures (id, name, billing_number) values (164, 'Anthropometric Characteristics Assessment using Oth Equip', '8157');
insert into procedures (id, name, billing_number) values (165, 'Extirpation of Matter from Upper Lip, External Approach', '7666');
insert into procedures (id, name, billing_number) values (166, 'Revision of Spacer in Left Carpal Joint, Perc Approach', '2939');
insert into procedures (id, name, billing_number) values (167, 'Fragmentation in Stomach, Via Natural or Artificial Opening', '2211');
insert into procedures (id, name, billing_number) values (168, 'Drainage of Left Axilla, Open Approach, Diagnostic', '0132');
insert into procedures (id, name, billing_number) values (169, 'Excision of Papillary Muscle, Perc Endo Approach', '3320');
insert into procedures (id, name, billing_number) values (170, 'Insertion of Radioact Elem into Up Back, Perc Endo Approach', '4494');
insert into procedures (id, name, billing_number) values (171, 'Restriction of Middle Esophagus, Via Opening', '8117');
insert into procedures (id, name, billing_number) values (172, 'Phototherapy, Circulatory, Multiple', '4198');
insert into procedures (id, name, billing_number) values (173, 'Inspection of Brain, Percutaneous Approach', '8383');
insert into procedures (id, name, billing_number) values (174, 'Extraction of Left Frontal Sinus, Open Approach', '0711');
insert into procedures (id, name, billing_number) values (175, 'Replace Neck Skin w Nonaut Sub, Full Thick, Extern', '4831');
insert into procedures (id, name, billing_number) values (176, 'Release Right Thorax Muscle, Open Approach', '7964');
insert into procedures (id, name, billing_number) values (177, 'Replacement of R Ulnar Art with Synth Sub, Open Approach', '585');
insert into procedures (id, name, billing_number) values (178, 'Drainage of Hyoid Bone, Percutaneous Approach, Diagnostic', '5498');
insert into procedures (id, name, billing_number) values (179, 'Drainage of Right Pleura, Open Approach', '0798');
insert into procedures (id, name, billing_number) values (180, 'Supplement L Ext Iliac Vein with Synth Sub, Perc Approach', '0844');
insert into procedures (id, name, billing_number) values (181, 'Destruction of Left Iris, Percutaneous Approach', '9341');
insert into procedures (id, name, billing_number) values (182, 'Excision of Right Thyroid Gland Lobe, Perc Endo Approach', '3779');
insert into procedures (id, name, billing_number) values (183, 'Replace R Lacrimal Bone w Synth Sub, Perc Endo', '6673');
insert into procedures (id, name, billing_number) values (184, 'Measurement of POC, Nervous Electr Activity, Endo', '5685');
insert into procedures (id, name, billing_number) values (185, 'Drainage of Bi Sperm Cord, Perc Endo Approach, Diagn', '9183');
insert into procedures (id, name, billing_number) values (186, 'Drainage of Vagina, Open Approach, Diagnostic', '3791');
insert into procedures (id, name, billing_number) values (187, 'Fragmentation in Mediastinum, Perc Endo Approach', '7733');
insert into procedures (id, name, billing_number) values (188, 'Replacement of Left Mandible with Autol Sub, Perc Approach', '2724');
insert into procedures (id, name, billing_number) values (189, 'Repair Left Foot Bursa and Ligament, Percutaneous Approach', '5847');
insert into procedures (id, name, billing_number) values (190, 'Insertion of Int Fix into R Knee Jt, Perc Endo Approach', '4542');
insert into procedures (id, name, billing_number) values (191, 'Removal of Other Device from Neck, Open Approach', '4223');
insert into procedures (id, name, billing_number) values (192, 'Repair Right Femoral Artery, Open Approach', '1269');
insert into procedures (id, name, billing_number) values (193, 'Replacement of Sternum with Autol Sub, Open Approach', '9635');
insert into procedures (id, name, billing_number) values (194, 'Bypass R Ext Iliac Art to R Ext Ilia w Autol Art, Open', '9359');
insert into procedures (id, name, billing_number) values (195, 'Replace of L Acetabulum with Synth Sub, Perc Endo Approach', '7844');
insert into procedures (id, name, billing_number) values (196, 'Removal of Ext Fix from L Pelvic Bone, Perc Endo Approach', '1665');
insert into procedures (id, name, billing_number) values (197, 'Supplement R Seminal Vesicle with Synth Sub, Open Approach', '3863');
insert into procedures (id, name, billing_number) values (198, 'Repair Male Reproductive System in POC, Via Opening', '9173');
insert into procedures (id, name, billing_number) values (199, 'Bypass L Com Iliac Art to L Femor A w Nonaut Sub, Perc Endo', '5163');
insert into procedures (id, name, billing_number) values (200, 'Revision of Autol Sub in L Low Femur, Extern Approach', '8674');
insert into procedures (id, name, billing_number) values (201, 'Sensory/Processing Assessment of Neuro Body using Oth Equip', '6501');
insert into procedures (id, name, billing_number) values (202, 'Release Ileum, Percutaneous Endoscopic Approach', '1300');
insert into procedures (id, name, billing_number) values (203, 'Fragmentation in Left Hepatic Duct, Open Approach', '9603');
insert into procedures (id, name, billing_number) values (204, 'Drainage of Left Foot Skin, External Approach', '4973');
insert into procedures (id, name, billing_number) values (205, 'Bypass Low Esophag to Stomach w Nonaut Sub, Perc Endo', '0042');
insert into procedures (id, name, billing_number) values (206, 'Revision of Autol Sub in Up Bursa/Lig, Perc Approach', '3582');
insert into procedures (id, name, billing_number) values (207, 'Drainage of Epiglottis, Via Natural or Artificial Opening', '7738');
insert into procedures (id, name, billing_number) values (208, 'Fusion Thor Jt w Intbd Fus Dev, Post Appr A Col, Open', '2009');
insert into procedures (id, name, billing_number) values (209, 'Extirpation of Matter from Left Sphenoid Bone, Open Approach', '3610');
insert into procedures (id, name, billing_number) values (210, 'Bypass R Axilla Art to L Up Arm Art w Synth Sub, Open', '9978');
insert into procedures (id, name, billing_number) values (211, 'Resection of Left Trunk Tendon, Open Approach', '3987');
insert into procedures (id, name, billing_number) values (212, 'Extirpation of Matter from R Renal Vein, Perc Endo Approach', '253');
insert into procedures (id, name, billing_number) values (213, 'Drainage of Right Brachial Artery, Perc Endo Approach', '7221');
insert into procedures (id, name, billing_number) values (214, 'Restriction of Trachea, Endo', '8936');
insert into procedures (id, name, billing_number) values (215, 'Cochlear Implant Assessment using Sound Field / Booth', '0779');
insert into procedures (id, name, billing_number) values (216, 'Reposition Lumbar Nerve, Open Approach', '6732');
insert into procedures (id, name, billing_number) values (217, 'Removal of Ext Fix from L Fibula, Perc Endo Approach', '1473');
insert into procedures (id, name, billing_number) values (218, 'Supplement R Frontal Bone w Nonaut Sub, Perc Endo', '8021');
insert into procedures (id, name, billing_number) values (219, 'Restriction of Common Bile Duct, Endo', '4449');
insert into procedures (id, name, billing_number) values (220, 'Fluoroscopy of Lumbar Facet Joint(s)', '700');
insert into procedures (id, name, billing_number) values (221, 'Drainage of Left Ulna, Open Approach, Diagnostic', '7094');
insert into procedures (id, name, billing_number) values (222, 'Remove of Autol Sub from L Thumb Phalanx, Perc Endo Approach', '3451');
insert into procedures (id, name, billing_number) values (223, 'Dilation of Left Internal Iliac Artery, Perc Endo Approach', '8172');
insert into procedures (id, name, billing_number) values (224, 'Extirpate matter from L Ext Iliac Art, Bifurc, Perc', '0443');
insert into procedures (id, name, billing_number) values (225, 'Removal of Radioactive Element from Right Breast, Endo', '5199');
insert into procedures (id, name, billing_number) values (226, 'Drainage of Left External Iliac Vein, Open Approach, Diagn', '8848');
insert into procedures (id, name, billing_number) values (227, 'Excision of Right Lower Eyelid, External Approach, Diagn', '6732');
insert into procedures (id, name, billing_number) values (228, 'Repair Left Kidney Pelvis, Open Approach', '271');
insert into procedures (id, name, billing_number) values (229, 'Drainage of Left Parotid Duct with Drain Dev, Perc Approach', '6651');
insert into procedures (id, name, billing_number) values (230, 'Bypass L Int Iliac Art to R Ext Ilia, Open Approach', '8672');
insert into procedures (id, name, billing_number) values (231, 'Repair Transverse Colon, Via Natural or Artificial Opening', '1736');
insert into procedures (id, name, billing_number) values (232, 'Drainage of Pharynx, Percutaneous Approach', '8427');
insert into procedures (id, name, billing_number) values (233, 'Supplement Right Fibula with Nonaut Sub, Perc Approach', '7911');
insert into procedures (id, name, billing_number) values (234, 'Extirpation of Matter from Portal Vein, Open Approach', '7124');
insert into procedures (id, name, billing_number) values (235, 'Destruction of Right Metatarsal, Perc Endo Approach', '1744');
insert into procedures (id, name, billing_number) values (236, 'Remove Contracept Dev from Low Extrem Subcu/Fascia, Perc', '9955');
insert into procedures (id, name, billing_number) values (237, 'Supplement Splenic Artery with Autol Sub, Perc Endo Approach', '4912');
insert into procedures (id, name, billing_number) values (238, 'Replacement of R Metatarsal with Synth Sub, Open Approach', '9505');
insert into procedures (id, name, billing_number) values (239, 'Revision of Drainage Device in Penis, Endo', '9734');
insert into procedures (id, name, billing_number) values (240, 'Occlusion of R Hepatic Duct with Intralum Dev, Perc Approach', '3616');
insert into procedures (id, name, billing_number) values (241, 'Fluoroscopy of Bi Pelvic Vein using H Osm Contrast', '8385');
insert into procedures (id, name, billing_number) values (242, 'Insertion of Infusion Dev into Low Vein, Perc Endo Approach', '0055');
insert into procedures (id, name, billing_number) values (243, 'Extraction of Post Neck Subcu/Fascia, Perc Approach', '8075');
insert into procedures (id, name, billing_number) values (244, 'Release Left Submaxillary Gland, Open Approach', '5491');
insert into procedures (id, name, billing_number) values (245, 'Reattachment of Penis, External Approach', '1366');
insert into procedures (id, name, billing_number) values (246, 'Division of Left Neck Muscle, Open Approach', '8459');
insert into procedures (id, name, billing_number) values (247, 'Fluoroscopy of Left Pelvic (Iliac) Veins using Oth Contrast', '8198');
insert into procedures (id, name, billing_number) values (248, 'Revision of Drainage Device in Chest Wall, Open Approach', '6751');
insert into procedures (id, name, billing_number) values (249, 'Fragmentation in Left Kidney Pelvis, Open Approach', '8781');
insert into procedures (id, name, billing_number) values (250, 'Drainage of Upper Gingiva with Drain Dev, Perc Approach', '7609');
insert into procedures (id, name, billing_number) values (251, 'Irrigation of Nose using Irrigating Substance, Endo', '0329');
insert into procedures (id, name, billing_number) values (252, 'Occlusion L Ext Iliac Art w Intralum Dev, Open', '4264');
insert into procedures (id, name, billing_number) values (253, 'Reposition Right Upper Leg Muscle, Open Approach', '3429');
insert into procedures (id, name, billing_number) values (254, 'Transfer L Hand Subcu/Fascia w Skin, Subcu, Fascia, Open', '4943');
insert into procedures (id, name, billing_number) values (255, 'Dilate L Com Carotid, Bifurc, w 4+ Intralum Dev, Perc Endo', '0221');
insert into procedures (id, name, billing_number) values (256, 'Excision of Ileum, Endo, Diagn', '1745');
insert into procedures (id, name, billing_number) values (257, 'Drainage of Left Nipple, Open Approach, Diagnostic', '2049');
insert into procedures (id, name, billing_number) values (258, 'Excision of Right Thorax Bursa and Ligament, Perc Approach', '8762');
insert into procedures (id, name, billing_number) values (259, 'Gastrointestinal System, Occlusion', '7392');
insert into procedures (id, name, billing_number) values (260, 'Replacement of Right Lacrimal Duct with Autol Sub, Endo', '8042');
insert into procedures (id, name, billing_number) values (261, 'Revise Infusion Pump in Low Extrem Subcu/Fascia, Open', '3199');
insert into procedures (id, name, billing_number) values (262, 'Removal of Ext Fix from R Tarsal Jt, Perc Endo Approach', '6419');
insert into procedures (id, name, billing_number) values (263, 'Drainage of Rectum, Percutaneous Endoscopic Approach', '7014');
insert into procedures (id, name, billing_number) values (264, 'Insertion of Oth Dev into L Up Extrem, Perc Endo Approach', '0022');
insert into procedures (id, name, billing_number) values (265, 'Hyperthermia of Peripheral Nerve', '8053');
insert into procedures (id, name, billing_number) values (266, 'Supplement Chordae Tendineae w Zooplastic, Perc Endo', '8752');
insert into procedures (id, name, billing_number) values (267, 'Bypass R Com Iliac Vein to Low Vein w Nonaut Sub, Open', '5694');
insert into procedures (id, name, billing_number) values (268, 'Division of Left Metatarsal, Perc Endo Approach', '5632');
insert into procedures (id, name, billing_number) values (269, 'Removal of Nonaut Sub from Lum Jt, Perc Approach', '3721');
insert into procedures (id, name, billing_number) values (270, 'Urinary System, Reposition', '6602');
insert into procedures (id, name, billing_number) values (271, 'Extirpation of Matter from R Pulm Vein, Perc Endo Approach', '1143');
insert into procedures (id, name, billing_number) values (272, 'Replacement of Up Tooth, All, with Nonaut Sub, Open Approach', '1519');
insert into procedures (id, name, billing_number) values (273, 'Extirpate of Matter from R Ethmoid Sinus, Perc Endo Approach', '8863');
insert into procedures (id, name, billing_number) values (274, 'Excision of Left Palatine Bone, Percutaneous Approach, Diagn', '4650');
insert into procedures (id, name, billing_number) values (275, 'Insertion of Intraluminal Device into Jejunum, Via Opening', '5899');
insert into procedures (id, name, billing_number) values (276, 'Transfer Left Hand Tendon, Percutaneous Endoscopic Approach', '9549');
insert into procedures (id, name, billing_number) values (277, 'Introduce Idarucizumab in Central Vein, Perc, New Tech 1', '3998');
insert into procedures (id, name, billing_number) values (278, 'Inspection of Left Carpal Joint, External Approach', '7869');
insert into procedures (id, name, billing_number) values (279, 'Bypass R Fallopian Tube to L Fallop w Synth Sub, Open', '8091');
insert into procedures (id, name, billing_number) values (280, 'Drainage of Stomach, Pylorus, Open Approach', '0294');
insert into procedures (id, name, billing_number) values (281, 'Drainage of Anus with Drainage Device, Open Approach', '3803');
insert into procedures (id, name, billing_number) values (282, 'Extirpation of Matter from Left Scapula, Perc Approach', '7679');
insert into procedures (id, name, billing_number) values (283, 'Bypass Thor Aorta Desc to Subclav w Autol Vn, Open', '7776');
insert into procedures (id, name, billing_number) values (284, 'Dilate R Thyroid Art, Bifurc, w Drug-elut Intra, Open', '5280');
insert into procedures (id, name, billing_number) values (285, 'Release Scrotum, Open Approach', '9145');
insert into procedures (id, name, billing_number) values (286, 'Revision of Int Fix in R Temporomandib Jt, Perc Approach', '0712');
insert into procedures (id, name, billing_number) values (287, 'Division of Right Thorax Bursa and Ligament, Perc Approach', '7742');
insert into procedures (id, name, billing_number) values (288, 'Destruction of Right Axillary Vein, Open Approach', '7985');
insert into procedures (id, name, billing_number) values (289, 'Repair Coronary Artery, One Artery, Perc Endo Approach', '7783');
insert into procedures (id, name, billing_number) values (290, 'Destruction of Bilateral Adrenal Glands, Perc Endo Approach', '411');
insert into procedures (id, name, billing_number) values (291, 'Insertion of Monopln Ext Fix into L Fibula, Open Approach', '3847');
insert into procedures (id, name, billing_number) values (292, 'Reattachment of Bi Fallopian Tube, Perc Endo Approach', '5759');
insert into procedures (id, name, billing_number) values (293, 'Release Acoustic Nerve, Open Approach', '4581');
insert into procedures (id, name, billing_number) values (294, 'Alteration of Right Lower Arm with Autol Sub, Perc Approach', '1483');
insert into procedures (id, name, billing_number) values (295, 'Reposition Oculomotor Nerve, Perc Endo Approach', '0886');
insert into procedures (id, name, billing_number) values (296, 'Dilation of Carina with Intralum Dev, Perc Endo Approach', '0231');
insert into procedures (id, name, billing_number) values (297, 'Supplement T-lum Jt with Autol Sub, Perc Endo Approach', '7809');
insert into procedures (id, name, billing_number) values (298, 'Bypass R Axilla Art to R Extracran Art w Nonaut Sub, Open', '2932');
insert into procedures (id, name, billing_number) values (299, 'Reattachment of Right Knee Bursa and Ligament, Open Approach', '9193');
insert into procedures (id, name, billing_number) values (300, 'Restrict R Post Tib Art w Extralum Dev, Perc Endo', '643');
insert into procedures (id, name, billing_number) values (301, 'Restriction of L Main Bronc with Intralum Dev, Perc Approach', '8388');
insert into procedures (id, name, billing_number) values (302, 'Change Other Device in Left Ear, External Approach', '8918');
insert into procedures (id, name, billing_number) values (303, 'Change Intermittent Pressure Device on Back', '4421');
insert into procedures (id, name, billing_number) values (304, 'Change Cast on Left Finger', '1955');
insert into procedures (id, name, billing_number) values (305, 'Excision of Accessory Nerve, Percutaneous Approach', '5524');
insert into procedures (id, name, billing_number) values (306, 'Replace of L Knee Tendon with Synth Sub, Perc Endo Approach', '2939');
insert into procedures (id, name, billing_number) values (307, 'Replacement of Left Eye with Nonaut Sub, Perc Approach', '3853');
insert into procedures (id, name, billing_number) values (308, 'Bypass R Com Iliac Art to B Com Ilia w Autol Art, Perc Endo', '8049');
insert into procedures (id, name, billing_number) values (309, 'Destruction of Abducens Nerve, Percutaneous Approach', '9066');
insert into procedures (id, name, billing_number) values (310, 'Insertion of Infusion Device into Lum Jt, Open Approach', '0612');
insert into procedures (id, name, billing_number) values (311, 'Extraction of Peroneal Nerve, Percutaneous Approach', '750');
insert into procedures (id, name, billing_number) values (312, 'Revision of Spacer in T-lum Jt, Perc Approach', '7865');
insert into procedures (id, name, billing_number) values (313, 'Repair Right Toe Phalangeal Joint, Open Approach', '3542');
insert into procedures (id, name, billing_number) values (314, 'Supplement Left Lower Leg with Autol Sub, Open Approach', '3821');
insert into procedures (id, name, billing_number) values (315, 'Occlusion Inf Mesent Vein w Intralum Dev, Open', '1365');
insert into procedures (id, name, billing_number) values (316, 'Removal of Drain Dev from R Pleural Cav, Perc Endo Approach', '8851');
insert into procedures (id, name, billing_number) values (317, 'LDR Brachytherapy of Hypopharynx using Iodine 125', '3765');
insert into procedures (id, name, billing_number) values (318, 'Computerized Tomography (CT Scan) of Left Toe(s)', '4682');
insert into procedures (id, name, billing_number) values (319, 'Insertion of Infusion Device into Pelvic Cav, Perc Approach', '9061');
insert into procedures (id, name, billing_number) values (320, 'Removal of Splint on Right Upper Extremity', '0295');
insert into procedures (id, name, billing_number) values (321, 'Caregiver Training in Bed Mobility using Orthosis', '3339');
insert into procedures (id, name, billing_number) values (322, 'MRI of Bi Jugular Vein using Oth Contrast', '8589');
insert into procedures (id, name, billing_number) values (323, 'LDR Brachytherapy of Ureter using Oth Isotope', '8776');
insert into procedures (id, name, billing_number) values (324, 'Release Portal Vein, Open Approach', '1291');
insert into procedures (id, name, billing_number) values (325, 'Traction of Left Thumb', '0202');
insert into procedures (id, name, billing_number) values (326, 'Supplement Uterine Support Struct w Synth Sub, Perc Endo', '6824');
insert into procedures (id, name, billing_number) values (327, 'Reposition L Low Arm & Wrist Tendon, Perc Endo Approach', '612');
insert into procedures (id, name, billing_number) values (328, 'Dilation of Gastric Vein with Intralum Dev, Perc Approach', '8555');
insert into procedures (id, name, billing_number) values (329, 'Reposition Right Metatarsal with Ext Fix, Perc Approach', '6019');
insert into procedures (id, name, billing_number) values (330, 'CT Scan of R Kidney using H Osm Contrast, Unenh, Enhance', '9183');
insert into procedures (id, name, billing_number) values (331, 'Excision of Left Frontal Bone, Open Approach', '4602');
insert into procedures (id, name, billing_number) values (332, 'Dynamic Orthosis Device Fitting using Orthosis', '4571');
insert into procedures (id, name, billing_number) values (333, 'Insertion of Feeding Device into Jejunum, Perc Endo Approach', '9031');
insert into procedures (id, name, billing_number) values (334, 'Release Left Acromioclavicular Joint, Open Approach', '5093');
insert into procedures (id, name, billing_number) values (335, 'Drainage of Bilateral Lungs, Via Opening, Diagn', '0822');
insert into procedures (id, name, billing_number) values (336, 'Insert of Infusion Dev into L Sacroiliac Jt, Perc Approach', '1234');
insert into procedures (id, name, billing_number) values (337, 'Staggered Spondaic Word Assessment using AV Equipment', '7987');
insert into procedures (id, name, billing_number) values (338, 'Revision of Ext Fix in L Radius, Open Approach', '3994');
insert into procedures (id, name, billing_number) values (339, 'Removal of Drainage Device from Lower Back, Perc Approach', '8814');
insert into procedures (id, name, billing_number) values (340, 'Excision of Coccygeal Joint, Open Approach, Diagnostic', '6299');
insert into procedures (id, name, billing_number) values (341, 'Contact Radiation of Oropharynx', '9203');
insert into procedures (id, name, billing_number) values (342, 'Introduction of Oth Antineoplastic into Ear, Extern Approach', '9670');
insert into procedures (id, name, billing_number) values (343, 'Drainage of Right Brachial Artery, Perc Endo Approach', '1259');
insert into procedures (id, name, billing_number) values (344, 'Beam Radiation of Kidney using Electrons, Intraoperative', '9524');
insert into procedures (id, name, billing_number) values (345, 'Dilation of R Radial Art with 4+ Intralum Dev, Perc Approach', '1879');
insert into procedures (id, name, billing_number) values (346, 'Occlusion of Left Lacrimal Duct, Open Approach', '9035');
insert into procedures (id, name, billing_number) values (347, 'Insert of Radioact Elem into Resp Tract, Perc Endo Approach', '5135');
insert into procedures (id, name, billing_number) values (348, 'Bypass R Int Jugular Vein to Up Vein w Autol Sub, Perc Endo', '7254');
insert into procedures (id, name, billing_number) values (349, 'Bypass Inf Vena Cava to Sup Mesent V w Nonaut Sub, Perc Endo', '1953');
insert into procedures (id, name, billing_number) values (350, 'Bypass R Ventricle to L Pulm Art w Zooplastic, Perc Endo', '7808');
insert into procedures (id, name, billing_number) values (351, 'Removal of Extralum Dev from Low Intest Tract, Open Approach', '7877');
insert into procedures (id, name, billing_number) values (352, 'Removal of Drainage Device from Cereb Vent, Extern Approach', '7989');
insert into procedures (id, name, billing_number) values (353, 'Detachment at Left 5th Toe, High, Open Approach', '7886');
insert into procedures (id, name, billing_number) values (354, 'Destruction of Right Middle Lung Lobe, Percutaneous Approach', '9743');
insert into procedures (id, name, billing_number) values (355, 'Removal of Cast on Right Hand', '3829');
insert into procedures (id, name, billing_number) values (356, 'Plain Radiography of Right Temporomandibular Joint', '0702');
insert into procedures (id, name, billing_number) values (357, 'Fusion Cerv Jt w Nonaut Sub, Post Appr A Col, Perc Endo', '4131');
insert into procedures (id, name, billing_number) values (358, 'CT Scan of Sacrum & Coccyx using Oth Contrast', '1371');
insert into procedures (id, name, billing_number) values (359, 'Transfuse Nonaut Antihemophilic in Central Vein, Perc', '8712');
insert into procedures (id, name, billing_number) values (360, 'Inspection of Right Lung, Via Natural or Artificial Opening', '4412');
insert into procedures (id, name, billing_number) values (361, 'Dilation of R Temporal Art with 2 Drug-elut, Open Approach', '6692');
insert into procedures (id, name, billing_number) values (362, 'Replace of Scalp Subcu/Fascia with Autol Sub, Open Approach', '4850');
insert into procedures (id, name, billing_number) values (363, 'Reposition Left Upper Femur with Intramed Fix, Open Approach', '9815');
insert into procedures (id, name, billing_number) values (364, 'Drainage of Innominate Artery, Perc Endo Approach, Diagn', '5788');
insert into procedures (id, name, billing_number) values (365, 'Excision of Pons, Percutaneous Approach', '2723');
insert into procedures (id, name, billing_number) values (366, 'Transfer Left Lower Leg Muscle with Skin, Perc Endo Approach', '7071');
insert into procedures (id, name, billing_number) values (367, 'Excision of Left Sublingual Gland, Open Approach, Diagnostic', '7669');
insert into procedures (id, name, billing_number) values (368, 'Supplement Lower Esophagus with Nonaut Sub, Via Opening', '9619');
insert into procedures (id, name, billing_number) values (369, 'Inspection of Retained POC, Extern Approach', '6551');
insert into procedures (id, name, billing_number) values (370, 'Bypass Gallbladder to L Hep Duc w Intralum Dev, Open', '8428');
insert into procedures (id, name, billing_number) values (371, 'Dilate Gastric Art, Bifurc, w 4 Drug-elut, Perc Endo', '7014');
insert into procedures (id, name, billing_number) values (372, 'Extirpate matter from R Com Iliac Vein, Perc Endo', '5303');
insert into procedures (id, name, billing_number) values (373, 'Excision of Left Upper Lung Lobe, Open Approach', '3768');
insert into procedures (id, name, billing_number) values (374, 'Bypass R Ext Iliac Art to Foot Art w Autol Art, Open', '5498');
insert into procedures (id, name, billing_number) values (375, 'Drainage of Jejunum, Open Approach', '4711');
insert into procedures (id, name, billing_number) values (376, 'Dilation of Inf Mesent Art with Intralum Dev, Open Approach', '2253');
insert into procedures (id, name, billing_number) values (377, 'Extirpation of Matter from Right Kidney, Perc Approach', '5451');
insert into procedures (id, name, billing_number) values (378, 'Excision of Left Rib, Percutaneous Approach', '8341');
insert into procedures (id, name, billing_number) values (379, 'Removal of Radioact Elem from GU Tract, Extern Approach', '7074');
insert into procedures (id, name, billing_number) values (380, 'Irrigation of Bil/Panc Tract using Irrigat, Endo', '0779');
insert into procedures (id, name, billing_number) values (381, 'Replacement of L Lacrml Duct with Synth Sub, Open Approach', '3840');
insert into procedures (id, name, billing_number) values (382, 'Insertion of Other Device into L Wrist, Open Approach', '7802');
insert into procedures (id, name, billing_number) values (383, 'Occlusion of Right Large Intestine, Percutaneous Approach', '8135');
insert into procedures (id, name, billing_number) values (384, 'Removal of Drainage Device from Bladder, Via Opening', '4671');
insert into procedures (id, name, billing_number) values (385, 'Excision of Duodenum, Percutaneous Approach', '8451');
insert into procedures (id, name, billing_number) values (386, 'Destruction of R Up Extrem Bursa/Lig, Perc Approach', '1663');
insert into procedures (id, name, billing_number) values (387, 'Drainage of Right Lower Femur with Drain Dev, Perc Approach', '8962');
insert into procedures (id, name, billing_number) values (388, 'Reposition Right Lower Femur, Open Approach', '6018');
insert into procedures (id, name, billing_number) values (389, 'Extirpation of Matter from L Sphenoid Sinus, Open Approach', '6599');
insert into procedures (id, name, billing_number) values (390, 'Restrict Thor Aorta Desc w Fenestr Dev 3+, Open', '1454');
insert into procedures (id, name, billing_number) values (391, 'Release Right Mastoid Sinus, Open Approach', '132');
insert into procedures (id, name, billing_number) values (392, 'Insertion of Artificial Sphincter into Anus, Perc Approach', '8075');
insert into procedures (id, name, billing_number) values (393, 'Restriction of Left Hand Artery, Open Approach', '1741');
insert into procedures (id, name, billing_number) values (394, 'Planar Nucl Med Imag of Myocardium using Oth Radionuclide', '0017');
insert into procedures (id, name, billing_number) values (395, 'Occlusion of L Radial Art with Extralum Dev, Perc Approach', '8957');
insert into procedures (id, name, billing_number) values (396, 'Occlusion of R Ext Carotid with Extralum Dev, Open Approach', '7840');
insert into procedures (id, name, billing_number) values (397, 'Repair Abdominal Aorta, Percutaneous Endoscopic Approach', '5589');
insert into procedures (id, name, billing_number) values (398, 'Reposition Right Vertebral Vein, Percutaneous Approach', '7171');
insert into procedures (id, name, billing_number) values (399, 'Insertion of Other Device into L Up Arm, Perc Endo Approach', '6692');
insert into procedures (id, name, billing_number) values (400, 'Release Left Epididymis, Percutaneous Endoscopic Approach', '4519');
insert into procedures (id, name, billing_number) values (401, 'Dilate R Int Iliac Art w Drug-elut Intra, Perc Endo', '9199');
insert into procedures (id, name, billing_number) values (402, 'Introduction of Oxazolidinones into Joints, Open Approach', '9463');
insert into procedures (id, name, billing_number) values (403, 'Auditory Processing Assessment using Other Equipment', '1641');
insert into procedures (id, name, billing_number) values (404, 'Supplement Right Temporal Bone with Autol Sub, Open Approach', '1741');
insert into procedures (id, name, billing_number) values (405, 'Imaging, Lymphatic System, Plain Radiography', '0072');
insert into procedures (id, name, billing_number) values (406, 'Measure of Peripheral Nervous Stimulator, Extern Approach', '8099');
insert into procedures (id, name, billing_number) values (407, 'Insertion of Intralum Dev into Sup Mesent Art, Open Approach', '6593');
insert into procedures (id, name, billing_number) values (408, 'Fluoroscopy of Left Wrist using Low Osmolar Contrast', '2509');
insert into procedures (id, name, billing_number) values (409, 'Dressing of Right Inguinal Region using Bandage', '6879');
insert into procedures (id, name, billing_number) values (410, 'Fusion of L Finger Phalanx Jt with Synth Sub, Perc Approach', '6711');
insert into procedures (id, name, billing_number) values (411, 'Inspection of Scrotum & Tunica, Perc Endo Approach', '0353');
insert into procedures (id, name, billing_number) values (412, 'Removal of Intralum Dev from Fallopian Tube, Perc Approach', '1300');
insert into procedures (id, name, billing_number) values (413, 'Removal of Drainage Device from C-thor Jt, Perc Approach', '3833');
insert into procedures (id, name, billing_number) values (414, 'Beam Radiation of Kidney using Photons <1 MeV', '8464');
insert into procedures (id, name, billing_number) values (415, 'Release Right Toe Phalangeal Joint, Percutaneous Approach', '1919');
insert into procedures (id, name, billing_number) values (416, 'Drainage of Right Lung, Perc Endo Approach, Diagn', '7827');
insert into procedures (id, name, billing_number) values (417, 'Alteration of Right Lower Arm with Synth Sub, Perc Approach', '3994');
insert into procedures (id, name, billing_number) values (418, 'Bypass L Ext Iliac Art to R Femor A w Autol Vn, Perc Endo', '0034');
insert into procedures (id, name, billing_number) values (419, 'Bypass R Pulm Art from Innom Art w Autol Vn, Open', '8705');
insert into procedures (id, name, billing_number) values (420, 'Drainage of Perineum Bursa and Ligament, Perc Approach', '6672');
insert into procedures (id, name, billing_number) values (421, 'CT Scan of L Wrist using Oth Contrast', '864');
insert into procedures (id, name, billing_number) values (422, 'Extirpation of Matter from R Acromioclav Jt, Perc Approach', '2009');
insert into procedures (id, name, billing_number) values (423, 'Repair Superior Mesenteric Artery, Open Approach', '6841');
insert into procedures (id, name, billing_number) values (424, 'Insertion of Spacer into Left Wrist Joint, Open Approach', '8445');
insert into procedures (id, name, billing_number) values (425, 'Inspection of Right Hand, Percutaneous Approach', '5849');
insert into procedures (id, name, billing_number) values (426, 'Fusion Thor Jt w Autol Sub, Post Appr P Col, Open', '8804');
insert into procedures (id, name, billing_number) values (427, 'Dilate R Peroneal Art, Bifurc, w Intralum Dev, Perc', '8128');
insert into procedures (id, name, billing_number) values (428, 'Occlusion of Left Ureter, Percutaneous Approach', '2621');
insert into procedures (id, name, billing_number) values (429, 'Excision of Right Foot Vein, Perc Endo Approach, Diagn', '5582');
insert into procedures (id, name, billing_number) values (430, 'Dilation of Right Lesser Saphenous Vein, Open Approach', '1121');
insert into procedures (id, name, billing_number) values (431, 'Bypass L Pulm Art from Subclav with Autol Art, Open Approach', '0120');
insert into procedures (id, name, billing_number) values (432, 'Osteopathic Treatment of Low Extrem w L Velocity H Ampl', '9453');
insert into procedures (id, name, billing_number) values (433, 'Excision of R Ankle Bursa/Lig, Open Approach, Diagn', '9336');
insert into procedures (id, name, billing_number) values (434, 'Drainage of Right Diaphragm, Perc Endo Approach, Diagn', '8375');
insert into procedures (id, name, billing_number) values (435, 'Supplement Lumbar Vertebra with Autol Sub, Open Approach', '8966');
insert into procedures (id, name, billing_number) values (436, 'Division of Right Metacarpal, Perc Endo Approach', '7922');
insert into procedures (id, name, billing_number) values (437, 'Extirpation of Matter from L Sternoclav Jt, Perc Approach', '4849');
insert into procedures (id, name, billing_number) values (438, 'Dilation of R Verteb Art with 4+ Intralum Dev, Open Approach', '0833');
insert into procedures (id, name, billing_number) values (439, 'Reposition Right Kidney Pelvis, Perc Endo Approach', '4495');
insert into procedures (id, name, billing_number) values (440, 'Removal of Ext Fix from L Metatarsal, Perc Endo Approach', '864');
insert into procedures (id, name, billing_number) values (441, 'Release Cerebral Hemisphere, Open Approach', '8534');
insert into procedures (id, name, billing_number) values (442, 'CT Scan Bi Salivary Gland w H Osm Contrast, Unenh, Enhance', '1434');
insert into procedures (id, name, billing_number) values (443, 'Tomo Nucl Med Imag of Low Extrem using Iodine 131', '8534');
insert into procedures (id, name, billing_number) values (444, 'Revision of Monitor Dev in Azygos Vein, Extern Approach', '9389');
insert into procedures (id, name, billing_number) values (445, 'Reposition Right Palatine Bone, External Approach', '540');
insert into procedures (id, name, billing_number) values (446, 'Drainage of Right Humeral Head with Drain Dev, Open Approach', '5212');
insert into procedures (id, name, billing_number) values (447, 'Removal of Drainage Device from Uterus and Cervix, Endo', '9741');
insert into procedures (id, name, billing_number) values (448, 'Drainage of Right Upper Eyelid, Open Approach', '1201');
insert into procedures (id, name, billing_number) values (449, 'Supplement Mesentery with Nonaut Sub, Open Approach', '7745');
insert into procedures (id, name, billing_number) values (450, 'Removal of Hearing Device from Left Inner Ear, Endo', '5051');
insert into procedures (id, name, billing_number) values (451, 'Beam Radiation of Mandible using Photons <1 MeV', '3800');
insert into procedures (id, name, billing_number) values (452, 'Drainage of R Ext Auditory Canal with Drain Dev, Via Opening', '8867');
insert into procedures (id, name, billing_number) values (453, 'Respiratory System, Dilation', '8173');
insert into procedures (id, name, billing_number) values (454, 'Destruction of Ascending Colon, Perc Endo Approach', '0699');
insert into procedures (id, name, billing_number) values (455, 'Bypass Inf Vena Cava to Sup Mesent V w Autol Art, Open', '9306');
insert into procedures (id, name, billing_number) values (456, 'Dilate R Ant Tib Art, Bifurc, w Drug-elut Intra, Perc Endo', '4199');
insert into procedures (id, name, billing_number) values (457, 'Bypass L Axilla Art to R Up Arm Art w Nonaut Sub, Open', '4594');
insert into procedures (id, name, billing_number) values (458, 'Excision of Thor Jt, Perc Endo Approach, Diagn', '6291');
insert into procedures (id, name, billing_number) values (459, 'Fragmentation in Right Fallopian Tube, Via Opening', '9628');
insert into procedures (id, name, billing_number) values (460, 'Bypass Left Kidney Pelvis to R Ureter, Perc Endo Approach', '4561');
insert into procedures (id, name, billing_number) values (461, 'Removal of Ext Fix from L Metatarsophal Jt, Open Approach', '8023');
insert into procedures (id, name, billing_number) values (462, 'Drainage of L Less Saphenous with Drain Dev, Perc Approach', '631');
insert into procedures (id, name, billing_number) values (463, 'Occlusion of R Axilla Art with Intralum Dev, Perc Approach', '8924');
insert into procedures (id, name, billing_number) values (464, 'Transfuse of Autol Factor IX into Periph Vein, Open Approach', '2342');
insert into procedures (id, name, billing_number) values (465, 'Imaging, Axial Skel, Exc Skull Facial, Ultrasound', '7924');
insert into procedures (id, name, billing_number) values (466, 'Repair Left Large Intestine, Percutaneous Approach', '9749');
insert into procedures (id, name, billing_number) values (467, 'Excision of Left Vocal Cord, Open Approach, Diagnostic', '3597');
insert into procedures (id, name, billing_number) values (468, 'Removal of Drain Dev from Thor Disc, Perc Endo Approach', '9331');
insert into procedures (id, name, billing_number) values (469, 'Excision of Esophagus, Open Approach, Diagnostic', '8941');
insert into procedures (id, name, billing_number) values (470, 'Insert of Facet Stabl Dev into T-lum Jt, Perc Endo Approach', '2185');
insert into procedures (id, name, billing_number) values (471, 'Revision of Autol Sub in R Acetabulum, Extern Approach', '8544');
insert into procedures (id, name, billing_number) values (472, 'Drainage of Left Shoulder Tendon, Open Approach, Diagnostic', '8866');
insert into procedures (id, name, billing_number) values (473, 'Release Scrotum, Percutaneous Endoscopic Approach', '4192');
insert into procedures (id, name, billing_number) values (474, 'Drainage of L Innom Vein with Drain Dev, Open Approach', '0523');
insert into procedures (id, name, billing_number) values (475, 'CT Scan of Pancreas using H Osm Contrast', '8712');
insert into procedures (id, name, billing_number) values (476, 'Bypass 3 Cor Art from L Int Mammary w Synth Sub, Perc Endo', '0602');
insert into procedures (id, name, billing_number) values (477, 'Change Drainage Device in Spinal Canal, External Approach', '0081');
insert into procedures (id, name, billing_number) values (478, 'Hyperthermia of Leg Skin', '5912');
insert into procedures (id, name, billing_number) values (479, 'Dressing of Left Lower Arm using Bandage', '9308');
insert into procedures (id, name, billing_number) values (480, 'Drainage of Sacral Nerve, Percutaneous Approach', '9063');
insert into procedures (id, name, billing_number) values (481, 'Supplement Vagina with Nonautologous Tissue Substitute, Endo', '4671');
insert into procedures (id, name, billing_number) values (482, 'Revision of Infusion Device in R Shoulder Jt, Open Approach', '7962');
insert into procedures (id, name, billing_number) values (483, 'Reposition Right Palatine Bone, Open Approach', '9306');
insert into procedures (id, name, billing_number) values (484, 'Inspection of Upper Muscle, Percutaneous Approach', '2439');
insert into procedures (id, name, billing_number) values (485, 'Drainage of Bi Vas Deferens with Drain Dev, Open Approach', '9464');
insert into procedures (id, name, billing_number) values (486, 'Drainage of Lower Jaw with Drain Dev, Perc Endo Approach', '6601');
insert into procedures (id, name, billing_number) values (487, 'Repair Transverse Colon, Via Natural or Artificial Opening', '8848');
insert into procedures (id, name, billing_number) values (488, 'Removal of Artificial Sphincter from Anus, Open Approach', '8916');
insert into procedures (id, name, billing_number) values (489, 'Drainage of Lower Esophagus with Drain Dev, Via Opening', '0159');
insert into procedures (id, name, billing_number) values (490, 'Plain Radiography of L Com Carotid using Oth Contrast', '8027');
insert into procedures (id, name, billing_number) values (491, 'Fluoroscopy of Bi Temporomand Jt using H Osm Contrast', '7014');
insert into procedures (id, name, billing_number) values (492, 'Excision of Right External Jugular Vein, Perc Approach', '2250');
insert into procedures (id, name, billing_number) values (493, 'Bypass R Innom Vein to Up Vein w Autol Vn, Perc Endo', '4349');
insert into procedures (id, name, billing_number) values (494, 'Dilate R Subclav Art, Bifurc, w 4+ Intralum Dev, Perc Endo', '1919');
insert into procedures (id, name, billing_number) values (495, 'Fusion C-thor Jt w Nonaut Sub, Post Appr P Col, Perc', '9035');
insert into procedures (id, name, billing_number) values (496, 'Dilate R Hand Art, Bifurc, w 4 Drug-elut, Open', '5673');
insert into procedures (id, name, billing_number) values (497, 'Insert Infusion Dev in R Int Jugular Vein, Perc', '736');
insert into procedures (id, name, billing_number) values (498, 'Removal of Synth Sub from Cereb Vent, Perc Approach', '1453');
insert into procedures (id, name, billing_number) values (499, 'Bypass Duodenum to Jejunum, Endo', '0016');
insert into procedures (id, name, billing_number) values (500, 'Supplement Cecum with Autol Sub, Perc Endo Approach', '9960');
insert into procedures (id, name, billing_number) values (501, 'Dilation of Right Ulnar Artery, Bifurcation, Perc Approach', '3613');
insert into procedures (id, name, billing_number) values (502, 'Insertion of Hybrid Ext Fix into R Radius, Open Approach', '8953');
insert into procedures (id, name, billing_number) values (503, 'Repair Pelvic Subcu/Fascia, Open Approach', '8582');
insert into procedures (id, name, billing_number) values (504, 'Extirpation of Matter from R Ext Carotid, Perc Endo Approach', '6149');
insert into procedures (id, name, billing_number) values (505, 'Indiv Counsel for Substance Abuse Treatment, Interpersonal', '9323');
insert into procedures (id, name, billing_number) values (506, 'Bypass R Com Iliac Art to Low Art w Nonaut Sub, Open', '8018');
insert into procedures (id, name, billing_number) values (507, 'Removal of Autol Sub from Abd Wall, Open Approach', '4971');
insert into procedures (id, name, billing_number) values (508, 'CT Scan of Abd using L Osm Contrast', '0153');
insert into procedures (id, name, billing_number) values (509, 'MRI of Bi Eye using Oth Contrast, Unenh, Enhance', '9772');
insert into procedures (id, name, billing_number) values (510, 'Dilate R Foot Art, Bifurc, w 3 Intralum Dev, Perc Endo', '1453');
insert into procedures (id, name, billing_number) values (511, 'Excision of Radial Nerve, Percutaneous Endoscopic Approach', '1919');
insert into procedures (id, name, billing_number) values (512, 'Remove Card Rhythm Dev from Trunk Subcu/Fascia, Open', '4904');
insert into procedures (id, name, billing_number) values (513, 'Removal of Other Device from Resp Tract, Perc Endo Approach', '8771');
insert into procedures (id, name, billing_number) values (514, 'Removal of Cast on Back', '7765');
insert into procedures (id, name, billing_number) values (515, 'Computerized Tomography (CT Scan) of Right Upper Extremity', '9014');
insert into procedures (id, name, billing_number) values (516, 'Occlusion of R Peroneal Art with Intralum Dev, Perc Approach', '8724');
insert into procedures (id, name, billing_number) values (517, 'Transfer Left Extraocular Muscle, Open Approach', '8261');
insert into procedures (id, name, billing_number) values (518, 'Bypass L Ureter to Bladder w Autol Sub, Perc Endo', '3401');
insert into procedures (id, name, billing_number) values (519, 'Insert Intralum Dev in R Ext Jugular Vein, Perc Endo', '9233');
insert into procedures (id, name, billing_number) values (520, 'Supplement L Ext Jugular Vein with Synth Sub, Open Approach', '2001');
insert into procedures (id, name, billing_number) values (521, 'Imaging, Urinary System, Magnetic Resonance Imaging (MRI)', '7271');
insert into procedures (id, name, billing_number) values (522, 'Supplement Cervcal Vertebra w Nonaut Sub, Perc Endo', '8925');
insert into procedures (id, name, billing_number) values (523, 'Release Thoracic Spinal Cord, Open Approach', '2756');
insert into procedures (id, name, billing_number) values (524, 'Replace Scalp Skin w Nonaut Sub, Part Thick, Extern', '1472');
insert into procedures (id, name, billing_number) values (525, 'Change Drainage Device in Ureter, External Approach', '9341');
insert into procedures (id, name, billing_number) values (526, 'Transfer Tongue, Open Approach', '0153');
insert into procedures (id, name, billing_number) values (527, 'Dilate of L Fem Art with Drug-elut Intra, Perc Endo Approach', '8689');
insert into procedures (id, name, billing_number) values (528, 'Dilation of L Popl Art with 2 Intralum Dev, Perc Approach', '6639');
insert into procedures (id, name, billing_number) values (529, 'Removal of Infusion Device from Lower Back, Perc Approach', '643');
insert into procedures (id, name, billing_number) values (530, 'Extirpation of Matter from L Shoulder Tendon, Open Approach', '0359');
insert into procedures (id, name, billing_number) values (531, 'Supplement Esophageal Vein w Nonaut Sub, Perc Endo', '6079');
insert into procedures (id, name, billing_number) values (532, 'Reposition Ampulla of Vater, Perc Endo Approach', '3523');
insert into procedures (id, name, billing_number) values (533, 'Alteration of Lower Jaw with Autol Sub, Perc Endo Approach', '5523');
insert into procedures (id, name, billing_number) values (534, 'Replace of L Hip Jt, Femoral with Synth Sub, Open Approach', '2933');
insert into procedures (id, name, billing_number) values (535, 'Replacement of Colic Vein with Autol Sub, Perc Endo Approach', '4239');
insert into procedures (id, name, billing_number) values (536, 'Bypass R Fallopian Tube to R Fallop w Autol Sub, Open', '8197');
insert into procedures (id, name, billing_number) values (537, 'Drainage of Left Upper Leg Tendon, Open Approach, Diagnostic', '5642');
insert into procedures (id, name, billing_number) values (538, 'Restrict of L Hand Art with Extralum Dev, Perc Endo Approach', '9334');
insert into procedures (id, name, billing_number) values (539, 'Replacement of Sup Vena Cava with Synth Sub, Open Approach', '4595');
insert into procedures (id, name, billing_number) values (540, 'Bypass R Com Iliac Art to R Com Ilia, Perc Endo Approach', '3402');
insert into procedures (id, name, billing_number) values (541, 'Dilate L Radial Art, Bifurc, w 4 Drug-elut, Open', '1153');
insert into procedures (id, name, billing_number) values (542, 'Revision of Intracard Pacer in Heart, Perc Endo Approach', '7768');
insert into procedures (id, name, billing_number) values (543, 'Revision of Nonaut Sub in L Sacroiliac Jt, Perc Approach', '581');
insert into procedures (id, name, billing_number) values (544, 'Bypass R Kidney Pelvis to Colon w Nonaut Sub, Open', '4946');
insert into procedures (id, name, billing_number) values (545, 'LDR Brachytherapy of Chest using Palladium 103', '8453');
insert into procedures (id, name, billing_number) values (546, 'Bypass Ascending Colon to Cutaneous, Open Approach', '4623');
insert into procedures (id, name, billing_number) values (547, 'Fluoroscopy of L Pelvic Vein using H Osm Contrast', '8114');
insert into procedures (id, name, billing_number) values (548, 'Replacement of Tongue with Synth Sub, Open Approach', '3173');
insert into procedures (id, name, billing_number) values (549, 'Destruction of Right Neck Lymphatic, Open Approach', '5734');
insert into procedures (id, name, billing_number) values (550, 'Repair Right Frontal Bone, Percutaneous Approach', '4503');
insert into procedures (id, name, billing_number) values (551, 'Removal of Nonaut Sub from R Tarsal, Perc Endo Approach', '8492');
insert into procedures (id, name, billing_number) values (552, 'Insert of Intspin Prcs Stabl Dev into Cerv Jt, Perc Approach', '311');
insert into procedures (id, name, billing_number) values (553, 'Revise Synth Sub in L Metatarsophal Jt, Perc Endo', '689');
insert into procedures (id, name, billing_number) values (554, 'Destruction of Pulmonary Trunk, Percutaneous Approach', '8195');
insert into procedures (id, name, billing_number) values (555, 'Repair Right Foot Muscle, Percutaneous Endoscopic Approach', '311');
insert into procedures (id, name, billing_number) values (556, 'Destruction of Left Ethmoid Bone, Perc Endo Approach', '0692');
insert into procedures (id, name, billing_number) values (557, 'Inspection of Right Temporomandibular Joint, Open Approach', '6823');
insert into procedures (id, name, billing_number) values (558, 'Control Bleeding in Respiratory Tract, Via Opening', '6574');
insert into procedures (id, name, billing_number) values (559, 'Revision of Implant Heart Assist in Heart, Perc Approach', '0753');
insert into procedures (id, name, billing_number) values (560, 'Extirpate of Matter from Sacral Symp Nrv, Perc Endo Approach', '0296');
insert into procedures (id, name, billing_number) values (561, 'Dilate R Renal Art, Bifurc, w 2 Intralum Dev, Perc Endo', '190');
insert into procedures (id, name, billing_number) values (562, 'Extirpate matter from L Int Carotid, Bifurc, Open', '8836');
insert into procedures (id, name, billing_number) values (563, 'Drainage of Right Elbow Bursa and Ligament, Open Approach', '7643');
insert into procedures (id, name, billing_number) values (564, 'Drainage of Right Large Intestine, Perc Endo Approach, Diagn', '042');
insert into procedures (id, name, billing_number) values (565, 'Extirpate matter from L Tunica Vaginalis, Perc Endo', '9635');
insert into procedures (id, name, billing_number) values (566, 'Insertion of Int Fix into R Acetabulum, Perc Approach', '3592');
insert into procedures (id, name, billing_number) values (567, 'Non-invasive Instrumental Status Assessment using Computer', '503');
insert into procedures (id, name, billing_number) values (568, 'Restriction of L Ulnar Art with Extralum Dev, Open Approach', '9022');
insert into procedures (id, name, billing_number) values (569, 'Transfer Tongue, External Approach', '0017');
insert into procedures (id, name, billing_number) values (570, 'Introduce of Oth Diagn Subst into Mouth/Phar, Perc Approach', '4679');
insert into procedures (id, name, billing_number) values (571, 'Introduce Oxazolidinones in Cran Cav/Brain, Open', '7922');
insert into procedures (id, name, billing_number) values (572, 'Fluoroscopy of R Pulm Vein using L Osm Contrast, Guidance', '3524');
insert into procedures (id, name, billing_number) values (573, 'Drainage of Bilateral Ovaries, Percutaneous Approach, Diagn', '5298');
insert into procedures (id, name, billing_number) values (574, 'Inspection of Right Sacroiliac Joint, Percutaneous Approach', '1179');
insert into procedures (id, name, billing_number) values (575, 'Restriction of Right Basilic Vein, Perc Endo Approach', '9303');
insert into procedures (id, name, billing_number) values (576, 'Bypass R Ext Iliac Art to L Femor A, Perc Endo Approach', '1273');
insert into procedures (id, name, billing_number) values (577, 'Dilate L Thyroid Art, Bifurc, w 4+ Intralum Dev, Perc Endo', '6012');
insert into procedures (id, name, billing_number) values (578, 'Reposition Right Radius with Ext Fix, Open Approach', '4951');
insert into procedures (id, name, billing_number) values (579, 'Fusion of Left Hip Joint with Int Fix, Open Approach', '8443');
insert into procedures (id, name, billing_number) values (580, 'Revision of Synthetic Substitute in L Patella, Open Approach', '1721');
insert into procedures (id, name, billing_number) values (581, 'Excision of Pancreatic Duct, Perc Endo Approach, Diagn', '3849');
insert into procedures (id, name, billing_number) values (582, 'Supplement Perineum Tendon w Synth Sub, Perc Endo', '3406');
insert into procedures (id, name, billing_number) values (583, 'Supplement R Cephalic Vein with Nonaut Sub, Open Approach', '6499');
insert into procedures (id, name, billing_number) values (584, 'Occlusion of Pancreatic Duct with Intralum Dev, Via Opening', '0836');
insert into procedures (id, name, billing_number) values (585, 'Revise of Autol Sub in L Finger Phalanx Jt, Extern Approach', '4141');
insert into procedures (id, name, billing_number) values (586, 'Excision of Skull, Percutaneous Endoscopic Approach', '4687');
insert into procedures (id, name, billing_number) values (587, 'Release L Up Extrem Bursa/Lig, Open Approach', '3789');
insert into procedures (id, name, billing_number) values (588, 'Gastrointestinal System, Destruction', '9977');
insert into procedures (id, name, billing_number) values (589, 'Release Left Internal Jugular Vein, Percutaneous Approach', '1811');
insert into procedures (id, name, billing_number) values (590, 'Removal of Spacer from Sacrococcygeal Jt, Perc Endo Approach', '3994');
insert into procedures (id, name, billing_number) values (591, 'Revision of Synth Sub in R Pelvic Bone, Perc Approach', '3852');
insert into procedures (id, name, billing_number) values (592, 'Removal of Other Device from GI Tract, Extern Approach', '1429');
insert into procedures (id, name, billing_number) values (593, 'Plain Radiography of Left Testicle using Other Contrast', '0120');
insert into procedures (id, name, billing_number) values (594, 'Insertion of Infusion Device into Testis, Perc Endo Approach', '0048');
insert into procedures (id, name, billing_number) values (595, 'Revision of Autol Sub in L Sacroiliac Jt, Perc Approach', '2751');
insert into procedures (id, name, billing_number) values (596, 'Resection of Ventricular Septum, Percutaneous Approach', '8344');
insert into procedures (id, name, billing_number) values (597, 'Destruction of Left Ureter, Percutaneous Approach', '3474');
insert into procedures (id, name, billing_number) values (598, 'Supplement R Sternoclav Jt w Autol Sub, Perc Endo', '2722');
insert into procedures (id, name, billing_number) values (599, 'Transfer Right Abdomen Tendon, Open Approach', '2502');
insert into procedures (id, name, billing_number) values (600, 'Insert Ring Ext Fix in R Femur Shaft, Perc Endo', '7123');
insert into procedures (id, name, billing_number) values (601, 'Extirpation of Matter from Right Frontal Bone, Perc Approach', '6093');
insert into procedures (id, name, billing_number) values (602, 'Repair Right Clavicle, External Approach', '3984');
insert into procedures (id, name, billing_number) values (603, 'Supplement Esophageal Vein with Synth Sub, Perc Approach', '1292');
insert into procedures (id, name, billing_number) values (604, 'Reposition Left Renal Artery, Percutaneous Approach', '7301');
insert into procedures (id, name, billing_number) values (605, 'Supplement L Femor Vein with Synth Sub, Perc Endo Approach', '6849');
insert into procedures (id, name, billing_number) values (606, 'Division of R Low Leg Subcu/Fascia, Open Approach', '1269');
insert into procedures (id, name, billing_number) values (607, 'Revision of Ext Fix in L Metacarpophal Jt, Extern Approach', '5551');
insert into procedures (id, name, billing_number) values (608, 'Bypass R Subclav Art to R Extracran Art, Open Approach', '9982');
insert into procedures (id, name, billing_number) values (609, 'Drainage of Right Brachial Vein, Percutaneous Approach', '2100');
insert into procedures (id, name, billing_number) values (610, 'Drainage of Left Elbow Joint, Perc Endo Approach', '9429');
insert into procedures (id, name, billing_number) values (611, 'Repair Right Upper Arm, Open Approach', '9960');
insert into procedures (id, name, billing_number) values (612, 'Supplement Left Ankle Joint with Nonaut Sub, Open Approach', '9995');
insert into procedures (id, name, billing_number) values (613, 'Excision of L Metacarpophal Jt, Perc Approach, Diagn', '5212');
insert into procedures (id, name, billing_number) values (614, 'Extirpation of Matter from Right Middle Lung Lobe, Endo', '3332');
insert into procedures (id, name, billing_number) values (615, 'Beam Radiation of Ear using Photons >10 MeV', '697');
insert into procedures (id, name, billing_number) values (616, 'Removal of Synth Sub from Fem Perineum, Perc Approach', '3814');
insert into procedures (id, name, billing_number) values (617, 'Extraction of R Low Leg Subcu/Fascia, Open Approach', '554');
insert into procedures (id, name, billing_number) values (618, 'Restriction of Jejunum with Extralum Dev, Open Approach', '4572');
insert into procedures (id, name, billing_number) values (619, 'Cochlear Implant Assessment using Hear Aid Equipment', '7661');
insert into procedures (id, name, billing_number) values (620, 'Beam Radiation of Pelvic Region using Photons >10 MeV', '7837');
insert into procedures (id, name, billing_number) values (621, 'Drainage of Right Lobe Liver, Perc Endo Approach', '8197');
insert into procedures (id, name, billing_number) values (622, 'Transfuse Autol Antihemophilic in Central Art, Open', '5201');
insert into procedures (id, name, billing_number) values (623, 'Resection of Upper Tooth, All, Open Approach', '4691');
insert into procedures (id, name, billing_number) values (624, 'Low Dose Rate (LDR) Brachytherapy of Larynx using Iodine 125', '8382');
insert into procedures (id, name, billing_number) values (625, 'Destruction of Left Vocal Cord, Endo', '7922');
insert into procedures (id, name, billing_number) values (626, 'Release Right Thyroid Gland Lobe, Open Approach', '6621');
insert into procedures (id, name, billing_number) values (627, 'Insert Infusion Dev in Vagina & Cul-de-sac, Perc', '3424');
insert into procedures (id, name, billing_number) values (628, 'Revision of Nonaut Sub in L Fibula, Open Approach', '0235');
insert into procedures (id, name, billing_number) values (629, 'Excision of Left Trunk Muscle, Open Approach', '4571');
insert into procedures (id, name, billing_number) values (630, 'Head and Facial Bones, Removal', '9914');
insert into procedures (id, name, billing_number) values (631, 'Release Lumbar Vertebral Disc, External Approach', '8583');
insert into procedures (id, name, billing_number) values (632, 'Supplement Right Elbow Region with Autol Sub, Open Approach', '5782');
insert into procedures (id, name, billing_number) values (633, 'Excision of Hymen, Percutaneous Endoscopic Approach, Diagn', '5021');
insert into procedures (id, name, billing_number) values (634, 'Fusion of R Finger Phalanx Jt with Int Fix, Open Approach', '5162');
insert into procedures (id, name, billing_number) values (635, 'Introduction of Serum/Tox/Vaccine into Nose, Via Opening', '4869');
insert into procedures (id, name, billing_number) values (636, 'Bypass Right Ureter to Cutan with Synth Sub, Open Approach', '8464');
insert into procedures (id, name, billing_number) values (637, 'Bypass L Ext Iliac Art to B Ext Ilia w Nonaut Sub, Perc Endo', '252');
insert into procedures (id, name, billing_number) values (638, 'Revision of Int Fix in Skull, Extern Approach', '1311');
insert into procedures (id, name, billing_number) values (639, 'Division of L Up Leg Subcu/Fascia, Perc Approach', '9343');
insert into procedures (id, name, billing_number) values (640, 'Alteration of Neck, Open Approach', '9773');
insert into procedures (id, name, billing_number) values (641, 'Drainage of L Up Extrem with Drain Dev, Open Approach', '4528');
insert into procedures (id, name, billing_number) values (642, 'Home Management Treatment using Electrotherapeutic Equipment', '9025');
insert into procedures (id, name, billing_number) values (643, 'Introduce of High dose IL-2 into Central Art, Open Approach', '4219');
insert into procedures (id, name, billing_number) values (644, 'Removal of Synth Sub from R Shoulder Jt, Open Approach', '5112');
insert into procedures (id, name, billing_number) values (645, 'Repair Left Internal Jugular Vein, Perc Endo Approach', '3779');
insert into procedures (id, name, billing_number) values (646, 'Alteration of L Knee with Nonaut Sub, Open Approach', '642');
insert into procedures (id, name, billing_number) values (647, 'Fluency Treatment using Voice Analysis Equipment', '8845');
insert into procedures (id, name, billing_number) values (648, 'Dilation of Splenic Art with Drug-elut Intra, Open Approach', '9324');
insert into procedures (id, name, billing_number) values (649, 'Dilate L Int Carotid, Bifurc, w 3 Drug-elut, Perc', '3982');
insert into procedures (id, name, billing_number) values (650, 'Release Dura Mater, Percutaneous Approach', '5679');
insert into procedures (id, name, billing_number) values (651, 'Revision of Other Device in Retroperitoneum, Perc Approach', '9432');
insert into procedures (id, name, billing_number) values (652, 'Extirpation of Matter from Rectum, Endo', '613');
insert into procedures (id, name, billing_number) values (653, 'Supplement Ileocecal Valve with Autol Sub, Endo', '9146');
insert into procedures (id, name, billing_number) values (654, 'Bypass Bi Ureter to Cutan with Autol Sub, Open Approach', '8128');
insert into procedures (id, name, billing_number) values (655, 'Occlusion of Lower Vein with Extralum Dev, Perc Approach', '9122');
insert into procedures (id, name, billing_number) values (656, 'Drainage of Right Carpal Joint, Open Approach', '8493');
insert into procedures (id, name, billing_number) values (657, 'Fusion Lumsac Jt w Autol Sub, Post Appr A Col, Open', '8379');
insert into procedures (id, name, billing_number) values (658, 'Bypass R Com Iliac Art to R Ext Ilia w Autol Vn, Open', '8546');
insert into procedures (id, name, billing_number) values (659, 'Drainage of L Metatarsophal Jt, Perc Approach, Diagn', '3341');
insert into procedures (id, name, billing_number) values (660, 'Bypass L Axilla Vein to Up Vein w Autol Vn, Perc Endo', '1370');
insert into procedures (id, name, billing_number) values (661, 'Insertion of Monitor Dev into Azygos Vein, Perc Approach', '3171');
insert into procedures (id, name, billing_number) values (662, 'Division of Left Wrist Bursa and Ligament, Perc Approach', '1651');
insert into procedures (id, name, billing_number) values (663, 'Excision of Right Eustachian Tube, Perc Endo Approach', '0042');
insert into procedures (id, name, billing_number) values (664, 'Beam Radiation of Back Skin using Heavy Particles', '0651');
insert into procedures (id, name, billing_number) values (665, 'Reposition Right Face Vein, Open Approach', '3813');
insert into procedures (id, name, billing_number) values (666, 'Restriction of Int Mamm, L Lymph, Perc Approach', '0581');
insert into procedures (id, name, billing_number) values (667, 'Drainage of Abd Subcu/Fascia with Drain Dev, Perc Approach', '0205');
insert into procedures (id, name, billing_number) values (668, 'Supplement R Axilla Vein with Nonaut Sub, Perc Endo Approach', '9155');
insert into procedures (id, name, billing_number) values (669, 'Transfusion of Nonaut WBC into Central Art, Open Approach', '9928');
insert into procedures (id, name, billing_number) values (670, 'Restriction of Colic Vein with Extralum Dev, Perc Approach', '7842');
insert into procedures (id, name, billing_number) values (671, 'Destruction of Left Nipple, Percutaneous Approach', '3977');
insert into procedures (id, name, billing_number) values (672, 'Alteration of Bi Breast with Synth Sub, Extern Approach', '8915');
insert into procedures (id, name, billing_number) values (673, 'Excision of Azygos Vein, Percutaneous Approach, Diagnostic', '2631');
insert into procedures (id, name, billing_number) values (674, 'Drainage of L Elbow Bursa/Lig, Perc Approach, Diagn', '524');
insert into procedures (id, name, billing_number) values (675, 'Insertion of Int Fix into L Knee Jt, Perc Endo Approach', '8301');
insert into procedures (id, name, billing_number) values (676, 'Drainage of Right Tympanic Membrane, Open Approach, Diagn', '5061');
insert into procedures (id, name, billing_number) values (677, 'Occlusion R Ext Jugular Vein w Extralum Dev, Perc', '3195');
insert into procedures (id, name, billing_number) values (678, 'Revision of Synth Sub in L Sacroiliac Jt, Perc Endo Approach', '3976');
insert into procedures (id, name, billing_number) values (679, 'Insertion of Other Device into R Knee, Perc Endo Approach', '4050');
insert into procedures (id, name, billing_number) values (680, 'Reattachment of Upper Tooth, Single, External Approach', '0125');
insert into procedures (id, name, billing_number) values (681, 'Restriction of Right Pulmonary Artery, Perc Endo Approach', '3989');
insert into procedures (id, name, billing_number) values (682, 'Drainage of Left Buttock, Perc Endo Approach, Diagn', '4542');
insert into procedures (id, name, billing_number) values (683, 'Replacement of Mitral Valve with Nonaut Sub, Open Approach', '3474');
insert into procedures (id, name, billing_number) values (684, 'Restrict L Post Tib Art w Extralum Dev, Perc Endo', '6241');
insert into procedures (id, name, billing_number) values (685, 'Resection of Glomus Jugulare, Open Approach', '1291');
insert into procedures (id, name, billing_number) values (686, 'Revision of Autol Sub in R Hip Jt, Extern Approach', '5597');
insert into procedures (id, name, billing_number) values (687, 'Excision of Right Lobe Liver, Open Approach, Diagnostic', '8965');
insert into procedures (id, name, billing_number) values (688, 'Bypass R Ext Iliac Art to L Ext Ilia w Autol Art, Perc Endo', '8397');
insert into procedures (id, name, billing_number) values (689, 'Revision of Int Fix in Nasal Bone, Open Approach', '738');
insert into procedures (id, name, billing_number) values (690, 'Supplement Lower Vein with Autol Sub, Perc Endo Approach', '5497');
insert into procedures (id, name, billing_number) values (691, 'Excision of Right Parietal Bone, Open Approach, Diagnostic', '8375');
insert into procedures (id, name, billing_number) values (692, 'Release Left Pelvic Bone, Percutaneous Approach', '5103');
insert into procedures (id, name, billing_number) values (693, 'Division of R Hand Subcu/Fascia, Open Approach', '3724');
insert into procedures (id, name, billing_number) values (694, 'Beam Radiation of Hard Palate using Neutron Capture', '0028');
insert into procedures (id, name, billing_number) values (695, 'Bypass R Ext Iliac Art to R Femor A w Nonaut Sub, Perc Endo', '8722');
insert into procedures (id, name, billing_number) values (696, 'Insert Int Fix in R Metatarsophal Jt, Perc Endo', '4103');
insert into procedures (id, name, billing_number) values (697, 'Reposition Left Carpal with Ext Fix, Perc Endo Approach', '9651');
insert into procedures (id, name, billing_number) values (698, 'Supplement Aort Valve fr Trunc Vlv w Zooplastic, Open', '3639');
insert into procedures (id, name, billing_number) values (699, 'Drainage of L Sternoclav Jt with Drain Dev, Open Approach', '1244');
insert into procedures (id, name, billing_number) values (700, 'Insertion of Monitor Dev into Ureter, Perc Endo Approach', '5561');
insert into procedures (id, name, billing_number) values (701, 'Muscle Performance Treatment of Integu Body using Oth Equip', '4219');
insert into procedures (id, name, billing_number) values (702, 'Release Right Trunk Muscle, Percutaneous Approach', '9434');
insert into procedures (id, name, billing_number) values (703, 'Excision of Bladder Neck, Via Opening, Diagn', '9357');
insert into procedures (id, name, billing_number) values (704, 'Bypass R Basilic Vein to Up Vein w Nonaut Sub, Perc Endo', '9114');
insert into procedures (id, name, billing_number) values (705, 'Release Right Zygomatic Bone, Perc Endo Approach', '4242');
insert into procedures (id, name, billing_number) values (706, 'Dilation of Left Fallopian Tube, Perc Endo Approach', '5684');
insert into procedures (id, name, billing_number) values (707, 'Bypass Innom Art to L Up Leg Art w Nonaut Sub, Open', '6571');
insert into procedures (id, name, billing_number) values (708, 'Plain Radiography of Left Ankle using High Osmolar Contrast', '8593');
insert into procedures (id, name, billing_number) values (709, 'Dilate Splenic Art, Bifurc, w 3 Drug-elut, Perc Endo', '9823');
insert into procedures (id, name, billing_number) values (710, 'Resection of L Abd Bursa/Lig, Perc Endo Approach', '4534');
insert into procedures (id, name, billing_number) values (711, 'Dilate of R Verteb Art with Intralum Dev, Perc Endo Approach', '6093');
insert into procedures (id, name, billing_number) values (712, 'Occlusion Ampulla Vater w Intralum Dev, Perc Endo', '7929');
insert into procedures (id, name, billing_number) values (713, 'Restriction of Anus, Percutaneous Approach', '3524');
insert into procedures (id, name, billing_number) values (714, 'MRI of Bi Renal Vein using Oth Contrast', '6594');
insert into procedures (id, name, billing_number) values (715, 'Supplement R Toe Phalanx Jt with Autol Sub, Open Approach', '7891');
insert into procedures (id, name, billing_number) values (716, 'Extirpate matter from R Subclav Art, Bifurc, Open', '0063');
insert into procedures (id, name, billing_number) values (717, 'CT Scan of Pancreas using L Osm Contrast, Unenh, Enhance', '5222');
insert into procedures (id, name, billing_number) values (718, 'Revision of Drainage Device in R Hip Jt, Perc Approach', '0753');
insert into procedures (id, name, billing_number) values (719, 'Reposition Left Knee Joint, Percutaneous Endoscopic Approach', '6094');
insert into procedures (id, name, billing_number) values (720, 'Destruction of Left External Jugular Vein, Open Approach', '0743');
insert into procedures (id, name, billing_number) values (721, 'Alteration of Neck with Autol Sub, Open Approach', '5300');
insert into procedures (id, name, billing_number) values (722, 'Measurement of Respiratory Volume, External Approach', '4412');
insert into procedures (id, name, billing_number) values (723, 'Reposition Right Wrist Joint with Ext Fix, Perc Approach', '8471');
insert into procedures (id, name, billing_number) values (724, 'Release Transverse Colon, Via Natural or Artificial Opening', '9465');
insert into procedures (id, name, billing_number) values (725, 'Introduce Autol Pancr Islet in Bil/Panc Tract, Via Opening', '5185');
insert into procedures (id, name, billing_number) values (726, 'Excision of Intracranial Artery, Percutaneous Approach', '0949');
insert into procedures (id, name, billing_number) values (727, 'Transfuse Nonaut Serum Albumin in Periph Art, Perc', '738');
insert into procedures (id, name, billing_number) values (728, 'Resection of Right Thorax Muscle, Perc Endo Approach', '1033');
insert into procedures (id, name, billing_number) values (729, 'Excision of Left Internal Carotid Artery, Perc Endo Approach', '3348');
insert into procedures (id, name, billing_number) values (730, 'Bypass Splenic Vein to Low Vein w Autol Sub, Open', '2261');
insert into procedures (id, name, billing_number) values (731, 'Replacement of Right Patella with Autol Sub, Perc Approach', '8777');
insert into procedures (id, name, billing_number) values (732, 'Dilation of 4+ Cor Art with 4+ Intralum Dev, Open Approach', '7535');
insert into procedures (id, name, billing_number) values (733, 'Excision of Conduction Mechanism, Percutaneous Approach', '9411');
insert into procedures (id, name, billing_number) values (734, 'Supplement R Verteb Art with Nonaut Sub, Open Approach', '8582');
insert into procedures (id, name, billing_number) values (735, 'Excision of Male Perineum, Open Approach', '0309');
insert into procedures (id, name, billing_number) values (736, 'Remove Autol Sub from L Temporomandib Jt, Perc Endo', '7071');
insert into procedures (id, name, billing_number) values (737, 'Drainage of Trachea, Endo, Diagn', '4791');
insert into procedures (id, name, billing_number) values (738, 'Drainage of Left Hand Tendon, Open Approach, Diagnostic', '3606');
insert into procedures (id, name, billing_number) values (739, 'Restriction of Esophageal Vein, Perc Endo Approach', '5141');
insert into procedures (id, name, billing_number) values (740, 'Occlusion of Left Lesser Saphenous Vein, Perc Approach', '734');
insert into procedures (id, name, billing_number) values (741, 'Division of Right Ovary, Percutaneous Endoscopic Approach', '9307');
insert into procedures (id, name, billing_number) values (742, 'Release Pituitary Gland, Percutaneous Approach', '4011');
insert into procedures (id, name, billing_number) values (743, 'Destruction of Left Tunica Vaginalis, Perc Endo Approach', '8480');
insert into procedures (id, name, billing_number) values (744, 'Replacement of Soft Palate with Synth Sub, Perc Approach', '5584');
insert into procedures (id, name, billing_number) values (745, 'Detachment at Left Foot, Complete 4th Ray, Open Approach', '8181');
insert into procedures (id, name, billing_number) values (746, 'Dilation of Left Temporal Artery, Percutaneous Approach', '5794');
insert into procedures (id, name, billing_number) values (747, 'Supplement R Up Extrem with Autol Sub, Perc Endo Approach', '1160');
insert into procedures (id, name, billing_number) values (748, 'Bypass Accessory Pancreatic Duct to Lg Int, Open Approach', '8344');
insert into procedures (id, name, billing_number) values (749, 'Supplement Uvula with Autol Sub, Open Approach', '5651');
insert into procedures (id, name, billing_number) values (750, 'Release Left Frontal Bone, Open Approach', '3882');
